
on: [push, pull_request]

name: Build

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: subosito/flutter-action@v1
      - run: |
          flutter pub get
          cd example
          flutter build apk
      - uses: actions/upload-artifact@v2
        with:
          name: example
          path: example/build/app/outputs/flutter-apk/app-release.apk 

